### ISSUE TITLE
没有反应点击保存

### ISSUE THREAD

**Issue by Evilc1** [bangtz/account_app_harmonyos#1]
大佬，那个记账写了价格和说明之后点击保存没有反应，我直接运行的你代码，有什么地方没配置好吗，谢谢解答

**Comment by banggx** [comment]
记账app使用到了首选项，数据库这些内容，需要使用模拟器预览体验，IDE里面的Preview模式不可以的哦

**Comment by Evilc1** [comment]
谢谢你大佬，感谢回答
